/// Types for the chat inference engine.
///
/// These are the nlp-engine's own types, independent of the app crate's trait types.
/// The app crate bridges between these types and the `ChatInferenceEngine` trait.
use serde::{Deserialize, Serialize};

/// Configuration for the chat inference engine.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatConfig {
    /// Context window size in tokens.
    pub n_ctx: u32,

    /// Default sampling temperature (0.0 = deterministic, higher = more creative).
    pub default_temperature: f32,

    /// Number of GPU layers to offload. Use 99 to offload all.
    pub n_gpu_layers: u32,

    /// Number of threads for CPU computation.
    pub n_threads: i32,
}

impl Default for ChatConfig {
    fn default() -> Self {
        Self {
            n_ctx: 32_768,
            default_temperature: 0.1,
            n_gpu_layers: 99,
            n_threads: std::thread::available_parallelism()
                .map(|p| p.get() as i32)
                .unwrap_or(4),
        }
    }
}

impl ChatConfig {
    /// Validate configuration values.
    pub fn validate(&self) -> Result<(), String> {
        if self.n_ctx == 0 {
            return Err("n_ctx must be greater than 0".to_string());
        }
        if self.default_temperature < 0.0 {
            return Err("default_temperature must be non-negative".to_string());
        }
        Ok(())
    }
}

/// A chat message input for inference.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessageInput {
    /// Role of the message sender: "system", "user", "assistant", or "tool".
    pub role: String,
    /// Text content of the message.
    pub content: String,
    /// For tool-result messages: the call ID that produced this result.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub call_id: Option<String>,
}

/// Specification of a tool the model may invoke.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolSpec {
    /// Unique name of the tool.
    pub name: String,
    /// Human-readable description of what the tool does.
    pub description: String,
    /// JSON Schema describing the tool's parameters.
    pub parameters_schema: serde_json::Value,
}

/// A chunk emitted during streaming inference.
#[derive(Debug, Clone)]
pub enum ChatChunk {
    /// A generated text token.
    Token(String),
    /// The model is starting a tool call.
    ToolCallStart {
        /// Unique identifier for this tool call.
        id: String,
        /// Name of the tool being invoked.
        name: String,
    },
    /// Incremental arguments JSON for an in-progress tool call.
    ToolCallArgs {
        /// Identifier matching the corresponding `ToolCallStart`.
        id: String,
        /// Partial JSON string of tool arguments.
        json: String,
    },
    /// Inference is complete.
    Done,
    /// An error occurred during streaming.
    Error(String),
}

/// Token usage statistics for a completed inference turn.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct ChatUsage {
    /// Number of tokens in the input prompt.
    pub prompt_tokens: u32,
    /// Number of tokens generated by the model.
    pub completion_tokens: u32,
}

/// Information about the currently loaded model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LoadedModelInfo {
    /// Path to the model file.
    pub model_path: String,
    /// Context window size.
    pub context_size: u32,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_chat_config() {
        let config = ChatConfig::default();
        assert_eq!(config.n_ctx, 32_768);
        assert!((config.default_temperature - 0.1).abs() < f32::EPSILON);
        assert_eq!(config.n_gpu_layers, 99);
        assert!(config.n_threads > 0);
    }

    #[test]
    fn test_chat_config_validation() {
        let config = ChatConfig::default();
        assert!(config.validate().is_ok());

        let bad = ChatConfig {
            n_ctx: 0,
            ..Default::default()
        };
        assert!(bad.validate().is_err());

        let bad2 = ChatConfig {
            default_temperature: -1.0,
            ..Default::default()
        };
        assert!(bad2.validate().is_err());
    }
}
